### ISSUE TITLE
Imageupload funktioniert nicht (ImageMagick/GraphicsMagic is not installed)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/ose_composition_hitobito_ag#1]
Imageupload funktioniert nicht (ImageMagick/GraphicsMagic is not installed)

**Comment by psunix** [comment]
image magick in rails-sphinx image hinzugefügt. https://github.com/puzzle/ose3-rails/commit/ef0fa9e1b9d85be0f1db6e5716927058f356de30
